name: MineTP
version: '2.1'
main: ljsure.cn.MineTP
api-version: '1.20'
commands:
  wtp:
    description: 传送命令
    usage: /wtp <玩家> 或 /wtp <x> <y> <z>
  killl:
    description: 自杀命令
    usage: /killl
  minetp:
    description: MineTP管理命令
    usage: /minetp <add|remove|list|radius|reload|info>

permissions:
  minetp.wtp:
    description: 使用传送命令
    default: true
  minetp.killl:
    description: 使用自杀命令
    default: true
  minetp.notify:
    description: 接收管理通知
    default: op
  minetp.admin:
    description: MineTP管理权限
    default: op